#SPDX-License-Identifier: MIT-0
---
# handlers file for webserver

- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart gunicorn
  systemd:
    name: gunicorn
    state: restarted

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded