[loadbalancer]
192.168.56.4

[webservers]
192.168.56.5
192.168.56.6

[database]
192.168.56.7

[multi:children]
loadbalancer
webservers
database

[multi:vars]
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key