#SPDX-License-Identifier: MIT-0
---
- name: Import the PGDG GPG signing key
  ansible.builtin.rpm_key:
    key: https://download.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL
    state: present

- name: Install official PGDG repository securely
  ansible.builtin.dnf:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_facts['distribution_major_version'] }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
    disable_gpg_check: false

- name: Install PostgreSQL
  ansible.builtin.dnf:
    name:
      - "postgresql{{ postgresql_version }}-server"
      - "postgresql{{ postgresql_version }}-contrib"
      - python3-psycopg2
    state: present

- name: check if postgresql is initialized
  ansible.builtin.stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pg_initialized

- name: View variable
  debug:
    var: pg_initialized

- name: Intialize postgresql if it's not yet been initialized 
  ansible.builtin.command: "/usr/pgsql-{{ postgresql_version }}/bin/postgresql-{{ postgresql_version }}-setup initdb"
  when: not pg_initialized.stat.exists

- name: configure postgresql.conf to listen on all interfaces
  ansible.builtin.lineinfile:
    path: "{{ postgresql_data_dir }}/postgresql.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line  }}"
  loop:
    - { regexp: '^#?listen_addresses\s*=', line: "listen_addresses = '*'" }
    - { regexp: '^#?port\s*=', line: "port = {{ postgresql_listen_port }}" }
    - { regexp: '^#?max_connections\s*=', line: "max_connections = {{ postgresql_max_connections }}" }
    - { regexp: '^#?shared_buffers\s*=', line: "shared_buffers = {{ postgresql_shared_buffers }}" }
    - { regexp: '^#?effective_cache_size\s*=', line: "effective_cache_size = {{ postgresql_effective_cache_size }}" }
  notify: restart_postgresql

- name: Configure pg_hba.conf file to allow only our web servers + localhost to authenticate
  ansible.builtin.blockinfile:
    path: "{{ postgresql_data_dir }}/pg_hba.conf"
    marker: "# {mark} Ansible stuff"
    block: |
      # Local app connections
      host      {{ postgresql_db }}     {{ postgresql_app_user }}       127.0.0.1/32        scram-sha-256
      host      {{ postgresql_db }}     {{ postgresql_app_user }}       ::1/128             scram-sha-256

      # Allow Django webservers
      {% for host_IP in postgresql_allowed_hosts %}
        host    {{ postgresql_db }}      {{ postgresql_app_user }}      {{ host_IP }}/32   scram-sha-256
      {% endfor %}

      # Local connections still use peer/ident
  notify: restart_postgresql 


- name: Start and enable PostgreSQL
  ansible.builtin.service:
    name: "postgresql-{{ postgresql_version }}"
    state: started
    enabled: true

- name: Create project database
  community.postgresql.postgresql_db:
    name: "{{ postgresql_db }}"
    encoding: UTF-8
    state: present
  become_user: postgres

- name: Create project database role/user
  community.postgresql.postgresql_user:
    name: "{{ postgresql_app_user }}"
    password: "{{ postgresql_app_password }}"
    state: present
    encrypted: true
  become_user: postgres
  no_log: true

- name: grant schema privileges to the app role
  community.postgresql.postgresql_privs:
    database: "{{ postgresql_db }}"
    state: present
    type: schema
    obj: public
    roles: "{{ postgresql_app_user }}"
    privs: ALL
  become_user: postgres

- name: Open TCP port 5432 permanently
  ansible.posix.firewalld:
    port: 5432/tcp
    permanent: true
    state: enabled
    immediate: true
  notify: reload firewalld