#SPDX-License-Identifier: MIT-0
---
# tasks file for webserver
- name: Install OS packages needed to build/run the app (nginx, gcc, headers)
  ansible.builtin.dnf:
    name:
      # - python3
      # - python3-pip
      - python3-devel
      - gcc
      - nginx
      - libpq-devel
      - openssl-devel
      - rsync
    state: present

- name: Create django project directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ django_user }}"
    group: "{{ django_group }}"
    mode: "0755"
  loop:
    - "{{ django_home }}"
    - "{{ django_app_base_dir }}"
    - "{{ django_app_base_dir }}/static"
    - "{{ django_app_base_dir }}/media"
    - "{{ django_app_base_dir }}/logs"
    - "{{ django_app_base_dir }}/run"
    
- name: Move django app from this app to django webserver nodes
  ansible.builtin.synchronize:
    src: "{{ playbook_dir }}/../django_app/"
    dest: "{{ django_app_base_dir }}"
    delete: true
    recursive: true
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=__pycache__"
      - "--exclude=*.pyc"
      - "--exclude=venv"
      - "--exclude=.env"
      - "--exclude=staticfiles"
      - "--exclude=static"       # <-- add
      - "--exclude=media"        # <-- add
      - "--exclude=logs"         # <-- add
      - "--exclude=run" 
  become: true
  become_user: "{{ django_user }}"
  notify: restart gunicorn 

- name: Create python virtual environment
  ansible.builtin.command:
    cmd: "python3 -m venv {{ django_app_venv_dir }}"
    creates: "{{ django_app_venv_dir }}/bin/activate"
  become_user: "{{ django_user }}"

- name: upgrade pip inside our virtual environment 
  ansible.builtin.pip:
    name: pip
    state: latest
    virtualenv: "{{ django_app_venv_dir }}"
  become_user: "{{ django_user }}"

- name: Install django, gunicorn, psycopg2-binary
  ansible.builtin.pip:
    requirements: "{{ django_app_base_dir }}/requirements.txt"
    virtualenv: "{{ django_app_venv_dir }}"
  become_user: "{{ django_user }}"
  notify: restart gunicorn


- name: Render .env file used by django's settings.py file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ django_app_base_dir }}/.env"
    owner: "{{ django_user }}"
    group: "{{ django_group }}"
    mode: "0600"
  no_log: true
  notify: restart gunicorn

- name: Collect static files into static_root
  command: "{{ django_app_venv_dir }}/bin/python manage.py collectstatic --noinput"
  args:
    chdir: "{{ django_app_base_dir }}"
  become: true
  become_user: "{{ django_user }}"
  environment:
    DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"
  changed_when: false   # collectstatic is noisy; we ignore "changed"   

- name: Apply database migrations
  command: "/opt/django/venv/bin/python manage.py migrate --noinput"
  args:
    chdir: "{{ django_app_base_dir }}"
  become: true
  become_user: "{{ django_user }}"
  environment:
    DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"
  register: migrate_result
  changed_when: "'No migrations to apply' not in migrate_result.stdout"
  run_once: true



  #######     Gunicorn stuff    ##############

# - name: Deploy the Gunicorn systemd socket unit
#   ansible.builtin.template:
#     src: gunicorn.socket.j2
#     dest: /etc/systemd/system/gunicorn.socket
#     mode: "0644"
#   when: use_unix_socket | bool
#   notify: reload systemd

- name: Install Gunicorm systemd unit from template
  ansible.builtin.template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
    mode: "0644"
  notify:
    - reload systemd
    - restart gunicorn

- name: Enable and start Gunicorn
  ansible.builtin.service:
    name: gunicorn
    state: started
    enabled: true
  

########## Nginx stuff ################
- name: Install Nginx site configuration
  ansible.builtin.template:
    src: nginx-django.conf.j2
    dest: /etc/nginx/conf.d/{{ project_name }}.conf
    mode: "0644"
  notify: reload nginx

- name: Remove the default Nginx welcome page (if present)
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: reload nginx

- name: Enable and start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true


