---
- name: General configuration for all hosts
  hosts: all
  gather_facts: true

  tasks:
    - name: Update system
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Add Epel repository
      ansible.builtin.dnf:
        name: 
          - epel-release
          - firewalld
          - python3
          - python3-pip
        state: present

    - name: Start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Allow HTTP through firewalld
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Disable SELinux # (For testing)
      ansible.posix.selinux:
        policy: "targeted"
        state: "disabled"
      register: selinux_result
      # Only reboot if the policy actually changed and a reboot is required
      notify: reboot

    - name: Create application group
      ansible.builtin.group:
        name: "{{ django_group }}"
        state: present
      when: inventory_hostname in groups['webservers'] or inventory_hostname in groups['database']

    - name: Create application user on all nodes
      ansible.builtin.user:
        name: "{{ django_user }}"
        group: "{{ django_group }}"
        shell: /sbin/nologin
        system: true
        create_home: true
        home: "{{ django_home }}"
      when: inventory_hostname in groups['webservers'] or inventory_hostname in groups['database']
  
  handlers:
    - name: reboot
      reboot:
        msg: "Reboot triggered by SELinux policy change"
        connect_timeout: 5
        reboot_timeout: 300


# Database Role 

- name: Configure PostgreSQL database server
  hosts: database
  become: true
  gather_facts: true
  tags: [database, postgresql]
  roles:
    - database
        
- name: Configure Django Webservers
  hosts: webservers
  become: true
  gather_facts: true
  tags: [webservers, postgresql]
  roles:
    - webserver


- name: "Configure the HAProxy load balancer"
  hosts: loadbalancer
  become: true
  gather_facts: true
  roles:
    - haproxy

        