---
- name: General configuration for all hosts
  hosts: all
  gather_facts: true

  tasks:
    - name: Add Epel repository
      ansible.builtin.dnf:
        name: epel-release
        state: present
    
    - name: Update system
      ansible.builtin.dnf:
        name: "*"
        state: latest
      
    - name: Update and install packages
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: Start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Create application group
      ansible.builtin.group:
        name: django_user
        state: present
      when: inventory_hostname in groups['webservers'] or inventory_hostname in groups['database']

    - name: Create application user on all nodes
      ansible.builtin.user:
        name: django_user
        group: django_user
        shell: /sbin/nologin
        system: true
        create_home: true
        home: "/opt/django"
      when: inventory_hostname in groups['webservers'] or inventory_hostname in groups['database']


# Database Role 

- name: Configure PostgreSQL database server
  hosts: database
  become: true
  gather_facts: true
  tags: [database, postgresql]
  roles:
    - database
        